[features]
seeds = true

[programs.mainnet]
lmax_multisig = "LMAXm1DhfBg1YMvi79gXdPfsJpYuJb9urGkGNa12hvJ"

[programs.devnet]
lmax_multisig = "LMAXm1DhfBg1YMvi79gXdPfsJpYuJb9urGkGNa12hvJ"

[programs.localnet]
lmax_multisig = "LMAXm1DhfBg1YMvi79gXdPfsJpYuJb9urGkGNa12hvJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/keypairs/default_wallet.json"
wallet_pub = "AeXDXCDe57eZq4ZLtB3RA9Cb5KRYPxYrFnQooay88Vc7"

[scripts]
test = "npx mocha --require ts-node/register -t 1000000 --exit tests/*Test.ts"

[path]
idl_path = "./target/idl/lmax_multisig.json"
binary_path = "./target/verifiable/lmax_multisig.so"
key_path = "./target/deploy/lmax_multisig-keypair.json"

[validator]
ledger_dir = "./.anchor/test-ledger"
